name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"
      - name: Debug files
        run: |
          pwd
          git ls-files | sed -n '1,50p'
          ls -la
          ls -la scripts || true
      - name: Build app
        run: ./scripts/buildprod.sh
